### ISSUE TITLE
Build html file with windows line-ending in mac/linux will fail

### ISSUE THREAD

**Issue by switer** [spatools/grunt-html-build#61]
GHB(grunt-html-build) replace raw contents's line-ending to \n and split lines with \n: 
```js
//#region Private Methods
function getBuildTags(content) {
        var lines = content.replace(/\r\n/g, '\n').split(/\n/),
```
In `transformContent` function,  raw-block-lines will be concated with `grunt.util.linefeed`(depend on system line-ending),  finally, GHB replace raw-block  of raw-content with result, but the raw-block's line ending has been modified, so raw-content will not match that block:

```js
    function transformContent(content, params, dest) {
        ......
        tags.forEach(function(tag) {
            var raw = tag.lines.join(EOL),
        ......

       content = content.replace(raw, function() {
             return result
       });
```

Resolve:
save `\r` char  for raw-block:
```js
function getBuildTags(content) {
    - var lines = content.replace(/\r\n/g, '\n').split(/\n/)
    + var lines = content.replace(/\n/g, '\n').split(/\n/)
```

```js
- regexTagStartTemplate = "<!--\\s*%parseTag%:(\\w+)\\s*(inline)?\\s*(optional)?\\s*(recursive)?\\s*(noprocess)?\\s*([^\\s]*)\\s*(?:\\[(.*)\\])?\\s*-->"
- regexTagEndTemplate = "<!--\\s*\\/%parseTag%\\s*-->"

+ regexTagStartTemplate = "<!--\\s*%parseTag%:(\\w+)\\s*(inline)?\\s*(optional)?\\s*(recursive)?\\s*(noprocess)?\\s*([^\\s]*)\\s*(?:\\[(.*)\\])?\\s*-->\s*"
+ regexTagEndTemplate = "<!--\\s*\\/%parseTag%\\s*-->\s*"
```

**Comment by sauvainr** [comment]
+1
FYI: I fix it my moving the line parsing in the main function and reconstruct the content from it:

 function transformContent(content, params, dest) {
        var lines = content.replace(/\r\n/g, '\n').split(/\n/); 
        var content = lines.join(EOL);
        var tags = getBuildTags(lines),

**Comment by SomaticIT** [comment]
Fixed in 0.5.1.
Thanks.

**Comment by mpostupalski** [comment]
Hi !

I think that this problem still exists. I have problems with "build:process" task when the file is created on Windows environment and grunt task runs on Linux environment. The file is just copied in new directory without any changes and tags:

```javascript
<!-- build:process -->
<!-- /build -->
```

also are not parsed. When I convert line end chars in the file to *nix format, then the file is not parsed on Windows but is parsed on *nix environment. Am I doing something wrong?

**Comment by sedrakpc** [comment]
Problem still exists!
